default-target-path: tmp
properties:
  - name: core-model-package
    value: de.ollie.healthtracker.core.service.model
  - name: core-port-persistence-package
    value: de.ollie.healthtracker.core.service.port.persistence
  - name: jpa-entity-package
    value: de.ollie.healthtracker.persistence.jpa.dbo
  - name: jpa-mapper-package
    value: de.ollie.healthtracker.persistence.jpa.mapper
  - name: jpa-repository-package
    value: de.ollie.healthtracker.persistence.jpa.repository
generators:
  - type: CLASS
    package: de.ollie.healthtracker.core.service.model
    resource-class-loader: org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader
    template: templates/core/Model.vc
    properties:
      - name: target-path
        value: service-interface/src/main/java
  - type: CLASS
    package: de.ollie.healthtracker.core.service.port.persistence
    target-file-name: ${UnitName}PersistencePort
    path: generator
    template: templates/core/PersistencePort.vc
    properties:
      - name: target-path
        value: service-interface/src/main/java
  - type: CLASS
    package: de.ollie.healthtracker.persistence.jpa.dbo
    resource-class-loader: org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader
    target-file-name: ${UnitName}Dbo
    template: templates/persistence/jpa/Dbo.vc
    properties:
      - name: target-path
        value: jpa-persistence/src/main/java
  - type: CLASS
    package: de.ollie.healthtracker.persistence.jpa.mapper
    resource-class-loader: org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader
    target-file-name: ${UnitName}DboMapper
    template: templates/persistence/jpa/DboMapper.vc
    properties:
      - name: target-path
        value: jpa-persistence/src/main/java
  - type: CLASS
    package: de.ollie.healthtracker.persistence.jpa.repository
    target-file-name: ${UnitName}DboRepository
    path: generator
    template: templates/jpa/DboRepository.vc
    properties:
      - name: target-path
        value: jpa-persistence/src/main/java
  - type: CLASS
    package: de.ollie.healthtracker.persistence.jpa
    target-file-name: ${UnitName}PersistenceJpaAdapter
    path: generator
    template: templates/jpa/PersistenceAdapter.vc
    properties:
      - name: target-path
        value: jpa-persistence/src/main/java
