default-target-path: tmp
properties:
  - name: model-package
    value: de.ollie.healthtracker.core.service.model
  - name: jpa-entity-package
    value: de.ollie.healthtracker.persistence.jpa.dbo
  - name: jpa-mapper-package
    value: de.ollie.healthtracker.persistence.jpa.mapper
  - name: jpa-repository-package
    value: de.ollie.healthtracker.persistence.jpa.repository
generators:
  - type: CLASS
    package: de.ollie.healthtracker.core.service.model
#    path: velocity-template-processing-adapter/src/main/resources/templates
#    template: Model.vc
    resource-class-loader: org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader
    template: templates/core/Model.vc
    properties:
      - name: target-path
        value: service-interface/src/main/java
# Settings to read from class path
#    resource-class-loader: org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader
#    template: templates/Model.vc
  - type: CLASS
    package: de.ollie.healthtracker.persistence.jpa.dbo
    resource-class-loader: org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader
    target-file-name: ${UnitName}Dbo
    template: templates/persistence/jpa/Dbo.vc
    properties:
      - name: target-path
        value: jpa-persistence/src/main/java
  - type: CLASS
    package: de.ollie.healthtracker.persistence.jpa.mapper
    resource-class-loader: org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader
    target-file-name: ${UnitName}DboMapper
    template: templates/persistence/jpa/DboMapper.vc
    properties:
      - name: target-path
        value: jpa-persistence/src/main/java
  - type: CLASS
    package: de.ollie.healthtracker.persistence.jpa.repository
    resource-class-loader: org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader
    target-file-name: ${UnitName}DboRepository
    template: templates/persistence/jpa/DboRepository.vc
    properties:
      - name: target-path
        value: jpa-persistence/src/main/java
